---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo
  annotations:
    kubernetes.io/change-cause: "Upgrading nginx version to 1.24"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  revisionHistoryLimit: 3
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      initContainers:
      - name: initialization
        image: {{ .Values.imageName }}
        command: ["/bin/bash", "-c"]
        args:
        - echo $DB_HOST > /usr/share/nginx/html/index.html && echo $(nginx -v 2>&1) >> /usr/share/nginx/html/index.html
        volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
        env:
        - name: ENVIRONMENT
          value: prod
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: config-demo
              key: DB_HOST
      containers:
      - name: demo-app
        image: {{ .Values.imageName }}
        volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"
      volumes:
      - name: shared
        emptyDir: {}