---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.max_surge }}
      maxUnavailable: {{ .Values.max_unavailable }}
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init
        image: nginx
        command: ["/bin/bash", "-c"]
        args:
        - echo $DB_HOST > /usr/share/nginx/html/index.html
        envFrom:
        - secretRef:
            name: demo-secret
        - configMapRef:
            name: demo-config
        volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx
        emptyDir: {}