---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-chart.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: demo
  type: {{ .Values.serviceType }}